### ISSUE TITLE
Unexpected keyword argument 'line_terminator' in .to_csv()

### ISSUE THREAD

**Issue by dact221** [cemanetwork/appmar2#3]
From https://github.com/cemanetwork/appmar/issues/7, issue opened by @murataksel:

There is a call to to_csv in the method extract_series. The call uses the keyword argument line_terminator='\n'

In Pandas 1.5, line_terminator was changed to lineterminator. A prompt solution is to downgrade Pandas to <1.5 (e.g. 1.4.4). For forward compatibility, the method call in APPMAR could be changed to lineterminator.

TODO:
- Change line_terminator to lineterminator in appmar2.py
- Create a new release (minor update)
- Create a package and upload it to PyPI (for easy pip install)

**Comment by dact221** [comment]
I found that .to_csv uses os.linesep by default as line terminator character, so no need to specify a character. Using the default makes the code more robust since os.linesep is `\n` for linux and `\r\n` for Windows.

TODO:
- Create a new release (minor update)
- Create a package and upload it to PyPI (for easy pip install/update)

**Comment by murataksel** [comment]
Did both of them in appmar2.py for windows OS. 
1. Change the line_terminator to lineterminator in appmar2.py
2. Change \n to \r\n 
Now it works.

**Comment by dact221** [comment]
Murat,

Glad to know that it worked. In the next few days I will create the minor release and update the PyPI package. Thank you very much for the feedback. Please, let me know if I can close this issue or if there is something more to check.

If you have any other questions, feel free to open a new issue; or if it is something beyond APPMAR (e.g. research/academia), you can even send me an email for us to share some ideas: diego.casas [at] ufpr.br

I will be happy to help

Diego

**Comment by murataksel** [comment]
Diego Hi,
Sure. You can close it I guess. Still downloading the whole data for process. I will keep you update while using your tool.
Best.
Murat.
